app = "splendor-backend-vluvdxvp"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
  strategy = "immediate"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  FASTAPI_COMMAND = "uvicorn"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "uvicorn app.api:app --host 0.0.0.0 --port 8080"
